import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from "react-i18next";
import { CalendarClock, Timer, MessageSquare, Clock, CheckCircle, XCircle, Power, PowerOff, Pencil, Trash2 } from "lucide-react";
import EmptyState from "../EmptyState";
export default function CronList({ jobs, isLoading, onToggle, onEdit, onRemove, describeSchedule, describeCron, describeIntervalMs, formatCronTimestamp, formatCronRelativeTime, }) {
    const { t } = useTranslation();
    if (isLoading) {
        return (_jsx("div", { className: "flex items-center justify-center h-32", children: _jsx("div", { className: "animate-spin rounded-full h-8 w-8 border-b-2 border-amber-600" }) }));
    }
    if (jobs.length === 0) {
        return _jsx(EmptyState, { icon: CalendarClock, title: t("workspace.noCronJobs"), description: t("workspace.noCronJobsDesc") });
    }
    return (_jsx("div", { className: "space-y-2", children: jobs.map((job, idx) => {
            const isEnabled = job.enabled;
            const scheduleDesc = describeSchedule(job.schedule);
            const nextRunRelative = formatCronRelativeTime(job.state?.nextRunAtMs || null);
            const lastRun = formatCronTimestamp(job.state?.lastRunAtMs || null);
            const lastStatus = job.state?.lastStatus;
            const lastError = job.state?.lastError;
            return (_jsx("div", { className: `group rounded-lg border transition-all hover:shadow-md ${isEnabled
                    ? "bg-green-50 dark:bg-green-900/20 border-green-200 dark:border-green-500/50"
                    : "bg-white dark:bg-dark-bg-card border-gray-200 dark:border-dark-border-subtle hover:border-gray-300 dark:hover:border-dark-border-default opacity-80 hover:opacity-100"}`, children: _jsxs("div", { className: "p-3", children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("div", { className: "flex items-center gap-2 min-w-0 flex-1", children: [_jsx("div", { className: `p-1.5 rounded-lg flex-shrink-0 ${isEnabled ? "bg-green-100 dark:bg-green-800/40" : "bg-gray-100 dark:bg-dark-bg-hover"}`, children: _jsx(CalendarClock, { className: `w-4 h-4 ${isEnabled ? "text-green-600 dark:text-green-400" : "text-gray-500 dark:text-dark-text-muted"}` }) }), _jsx("div", { className: "min-w-0", children: _jsxs("div", { className: "flex items-center gap-2 flex-wrap", children: [_jsx("h3", { className: "font-semibold text-gray-900 dark:text-dark-text-primary text-sm truncate", children: job.name || job.id }), isEnabled ? (_jsx("span", { className: "px-1.5 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-700 dark:text-green-400 text-[10px] rounded-full flex-shrink-0", children: t("workspace.enabled") })) : (_jsx("span", { className: "px-1.5 py-0.5 bg-gray-100 dark:bg-dark-bg-hover text-gray-600 dark:text-dark-text-muted text-[10px] rounded-full flex-shrink-0", children: t("workspace.disabled") }))] }) })] }), _jsxs("div", { className: "flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity ml-2 flex-shrink-0", children: [_jsx("button", { onClick: () => onToggle(job), className: `p-1 rounded-md transition-colors ${isEnabled
                                                ? "text-green-600 dark:text-green-400 hover:bg-green-100 dark:hover:bg-green-900/30"
                                                : "text-gray-400 hover:bg-gray-100 dark:hover:bg-dark-bg-hover"}`, title: isEnabled ? t("workspace.disable") : t("workspace.enable"), children: isEnabled ? _jsx(Power, { className: "w-3.5 h-3.5" }) : _jsx(PowerOff, { className: "w-3.5 h-3.5" }) }), _jsx("button", { onClick: () => onEdit(job), className: "p-1 text-gray-400 hover:text-amber-600 dark:hover:text-amber-400 hover:bg-amber-50 dark:hover:bg-amber-900/30 rounded-md transition-colors", title: t("workspace.cronEditJob"), children: _jsx(Pencil, { className: "w-3.5 h-3.5" }) }), _jsx("button", { onClick: () => onRemove(job), className: "p-1 text-gray-400 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/30 rounded-md transition-colors", title: t("workspace.cronRemoveJob"), children: _jsx(Trash2, { className: "w-3.5 h-3.5" }) })] })] }), _jsxs("div", { className: "flex items-center gap-2 mb-1.5", children: [_jsx(Timer, { className: `w-3 h-3 flex-shrink-0 ${isEnabled ? "text-green-500 dark:text-green-400" : "text-gray-400 dark:text-dark-text-muted"}` }), _jsx("span", { className: `text-xs font-medium truncate ${isEnabled ? "text-green-700 dark:text-green-300" : "text-gray-600 dark:text-dark-text-secondary"}`, children: scheduleDesc }), job.schedule?.kind === "cron" && job.schedule.expr && (_jsxs("code", { className: "text-[9px] text-gray-400 dark:text-dark-text-muted font-mono flex-shrink-0", children: ["(", job.schedule.expr, ")"] }))] }), job.payload?.message && (_jsxs("div", { className: "flex items-start gap-2 mb-1.5", children: [_jsx(MessageSquare, { className: "w-3 h-3 text-gray-400 dark:text-dark-text-muted flex-shrink-0 mt-0.5" }), _jsx("p", { className: "text-[11px] text-gray-600 dark:text-dark-text-secondary break-words line-clamp-2 leading-relaxed", children: job.payload.message })] })), _jsxs("div", { className: "flex flex-wrap items-center gap-x-2 gap-y-1 text-[10px] text-gray-400 dark:text-dark-text-muted pt-1.5 border-t border-gray-200/50 dark:border-dark-border-subtle/50", children: [job.state?.nextRunAtMs && (_jsxs("div", { className: "flex items-center gap-1", children: [_jsx(Clock, { className: "w-2.5 h-2.5" }), _jsxs("span", { children: [t("workspace.cronNextRun"), ": ", nextRunRelative] })] })), lastRun !== "-" && (_jsxs("div", { className: "flex items-center gap-1", children: [lastStatus === "success" ? (_jsx(CheckCircle, { className: "w-2.5 h-2.5 text-green-500" })) : lastStatus === "failed" ? (_jsx(XCircle, { className: "w-2.5 h-2.5 text-red-500" })) : (_jsx(Clock, { className: "w-2.5 h-2.5" })), _jsxs("span", { children: [t("workspace.cronLastRun"), ": ", lastRun] })] }))] }), lastError && (_jsx("div", { className: "mt-1.5 px-2 py-1 bg-red-50 dark:bg-red-900/20 border border-red-100 dark:border-red-800/40 rounded-md", children: _jsx("p", { className: "text-[10px] text-red-600 dark:text-red-400", children: lastError }) }))] }) }, job.id || idx));
        }) }));
}
