import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from "react-i18next";
import { Search, Filter, X } from "lucide-react";
export default function SkillFilters({ searchQuery, category, showInstalled, onSearchChange, onCategoryChange, onToggleInstalled, categories, }) {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-400 dark:text-dark-text-muted" }), _jsx("input", { type: "text", placeholder: t("skills.searchPlaceholder"), value: searchQuery, onChange: (e) => onSearchChange(e.target.value), className: "w-full pl-10 pr-4 py-2 bg-gray-50 dark:bg-dark-bg-sidebar border border-gray-200 dark:border-dark-border-subtle rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 text-sm" })] }), _jsxs("div", { children: [_jsxs("div", { className: "flex items-center justify-between mb-2", children: [_jsxs("label", { className: "text-sm font-medium text-gray-700 dark:text-dark-text-secondary flex items-center gap-2", children: [_jsx(Filter, { className: "w-4 h-4" }), t("skills.categoryFilter")] }), category && (_jsxs("button", { onClick: () => onCategoryChange(""), className: "text-xs text-blue-600 dark:text-blue-400 hover:underline flex items-center gap-1", children: [_jsx(X, { className: "w-3 h-3" }), t("skills.clearFilter")] }))] }), _jsxs("div", { className: "flex flex-wrap gap-2", children: [_jsx("button", { onClick: () => onCategoryChange(""), className: `px-3 py-1 rounded-full text-xs font-medium transition-colors ${!category
                                    ? "bg-blue-600 text-white"
                                    : "bg-gray-100 dark:bg-dark-bg-hover text-gray-600 dark:text-dark-text-muted"}`, children: t("skills.allCategories") }), categories.map((cat) => (_jsx("button", { onClick: () => onCategoryChange(cat), className: `px-3 py-1 rounded-full text-xs font-medium transition-colors ${category === cat
                                    ? "bg-blue-600 text-white"
                                    : "bg-gray-100 dark:bg-dark-bg-hover text-gray-600 dark:text-dark-text-muted"}`, children: cat }, cat)))] })] }), _jsx("div", { className: "flex items-center gap-2", children: _jsx("button", { onClick: onToggleInstalled, className: `px-3 py-1.5 rounded-lg text-sm font-medium transition-colors border-2 ${showInstalled
                        ? "border-green-500 bg-green-50 dark:bg-green-900/20 text-green-700 dark:text-green-400"
                        : "border-gray-200 dark:border-dark-border-subtle text-gray-600 dark:text-dark-text-muted hover:border-gray-300"}`, children: t("skills.showInstalled") }) })] }));
}
