import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * 配置概览卡片组件
 */
import { useTranslation } from "react-i18next";
import { Server, Bot, MessageSquare } from "lucide-react";
export default function ConfigOverviewCards({ config }) {
    const { t } = useTranslation();
    if (!config)
        return null;
    return (_jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Server, { className: "w-5 h-5 text-blue-500" }), _jsx("span", { className: "text-base font-medium text-gray-700 dark:text-dark-text-primary", children: t("dashboard.llmProvider") })] }), (() => {
                        const configuredProviders = config.providers
                            ? Object.entries(config.providers).filter(([_, p]) => p && p.apiKey && String(p.apiKey).trim() !== "")
                            : [];
                        return configuredProviders.length > 0 ? (_jsx("div", { className: "space-y-2", children: configuredProviders.map(([providerKey]) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-dark-text-secondary", children: providerKey }), _jsx("span", { className: "px-2 py-0.5 bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400 text-xs rounded-full", children: t("dashboard.configured") })] }, providerKey))) })) : (_jsx("p", { className: "text-sm text-gray-400 dark:text-dark-text-muted", children: t("dashboard.noConfiguration") }));
                    })()] }), _jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(Bot, { className: "w-5 h-5 text-indigo-500" }), _jsx("span", { className: "text-base font-medium text-gray-700 dark:text-dark-text-primary", children: t("dashboard.agentConfig") })] }), config.agents?.defaults ? (_jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.model") }), _jsx("span", { className: "text-sm font-medium text-gray-700 dark:text-dark-text-secondary truncate max-w-[140px]", title: config.agents.defaults.model, children: config.agents.defaults.model || '-' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.maxTokens") }), _jsx("span", { className: "text-sm font-medium text-gray-700 dark:text-dark-text-secondary", children: config.agents.defaults.maxTokens || '-' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.maxToolIterations") }), _jsx("span", { className: "text-sm font-medium text-gray-700 dark:text-dark-text-secondary", children: config.agents.defaults.maxToolIterations || '-' })] }), _jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.temperature") }), _jsx("span", { className: "text-sm font-medium text-gray-700 dark:text-dark-text-secondary", children: config.agents.defaults.temperature || '-' })] })] })) : (_jsx("p", { className: "text-sm text-gray-400 dark:text-dark-text-muted", children: t("dashboard.noConfiguration") }))] }), _jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-4", children: [_jsx(MessageSquare, { className: "w-5 h-5 text-purple-500" }), _jsx("span", { className: "text-base font-medium text-gray-700 dark:text-dark-text-primary", children: t("dashboard.messageChannels") })] }), config.channels && Object.keys(config.channels).length > 0 ? (_jsxs("div", { className: "space-y-2", children: [Object.entries(config.channels)
                                .filter(([_, channel]) => channel?.enabled)
                                .slice(0, 4)
                                .map(([channelKey]) => (_jsxs("div", { className: "flex items-center justify-between", children: [_jsx("span", { className: "text-sm text-gray-600 dark:text-dark-text-secondary capitalize", children: channelKey }), _jsx("span", { className: "px-2 py-0.5 bg-blue-100 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 text-xs rounded-full", children: t("config.enabled") })] }, channelKey))), Object.values(config.channels).filter((c) => c?.enabled).length === 0 && (_jsx("p", { className: "text-sm text-gray-400 dark:text-dark-text-muted", children: t("dashboard.noEnabledChannels") })), Object.values(config.channels).filter((c) => c?.enabled).length > 4 && (_jsxs("p", { className: "text-sm text-gray-400 dark:text-dark-text-muted", children: ["+", Object.values(config.channels).filter((c) => c?.enabled).length - 4, " ", t("dashboard.more")] }))] })) : (_jsx("p", { className: "text-sm text-gray-400 dark:text-dark-text-muted", children: t("dashboard.noConfiguration") }))] })] }));
}
