import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
/**
 * 状态卡片组件
 */
import { useTranslation } from "react-i18next";
import { Activity, Zap, Clock, Info } from "lucide-react";
export default function StatusCards({ status, nanobotVersion }) {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "grid grid-cols-2 md:grid-cols-4 gap-4", children: [_jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Activity, { className: "w-5 h-5 text-blue-500" }), _jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.systemStatus") })] }), _jsx("p", { className: `text-2xl font-semibold ${status.running ? "text-green-600 dark:text-green-400" : "text-gray-400 dark:text-dark-text-muted"}`, children: status.running ? t("dashboard.active") : t("dashboard.offline") })] }), _jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Zap, { className: "w-5 h-5 text-amber-500" }), _jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.servicePort") })] }), _jsx("p", { className: "text-2xl font-semibold text-gray-900 dark:text-dark-text-primary", children: status.port || "N/A" })] }), _jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center gap-2 mb-3", children: [_jsx(Clock, { className: "w-5 h-5 text-purple-500" }), _jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.uptime") })] }), _jsx("p", { className: "text-2xl font-semibold text-gray-900 dark:text-dark-text-primary", children: status.uptime || "--:--" })] }), _jsxs("div", { className: "p-5 bg-white dark:bg-dark-bg-card rounded-xl border border-gray-200 dark:border-dark-border-subtle transition-colors duration-200", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Info, { className: "w-5 h-5 text-indigo-500" }), _jsx("span", { className: "text-sm text-gray-500 dark:text-dark-text-muted", children: t("dashboard.version") })] }), _jsx("span", { className: `px-2 py-1 rounded-lg text-xs font-medium ${nanobotVersion?.installed
                                    ? "bg-green-100 dark:bg-green-900/30 text-green-600 dark:text-green-400"
                                    : "bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400"}`, children: nanobotVersion?.installed ? t("dashboard.installed") : t("dashboard.notInstalled") })] }), _jsx("p", { className: "text-lg font-semibold text-gray-900 dark:text-dark-text-primary truncate", title: nanobotVersion?.version || nanobotVersion?.message || t("dashboard.detecting"), children: nanobotVersion?.version || nanobotVersion?.message || t("dashboard.detecting") })] })] }));
}
