import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useTranslation } from "react-i18next";
import { Plug, ChevronUp, ChevronDown, Globe, Terminal, Plus } from "lucide-react";
import EmptyState from "../../EmptyState";
export default function McpServerSection({ mcpServersConfig, expanded, onToggle, onAddServer, onEditServer, onToggleServer, }) {
    const { t } = useTranslation();
    return (_jsxs("div", { className: "bg-white dark:bg-dark-bg-card rounded-lg border border-gray-200 dark:border-dark-border-subtle overflow-hidden transition-colors duration-200", children: [_jsxs("button", { onClick: onToggle, className: "w-full p-5 flex items-center justify-between hover:bg-gray-50 dark:hover:bg-dark-bg-hover transition-colors", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx("div", { className: "p-2 bg-emerald-50 dark:bg-emerald-900/30 rounded-lg", children: _jsx(Plug, { className: "w-5 h-5 text-emerald-600 dark:text-emerald-400" }) }), _jsx("h2", { className: "text-lg font-semibold text-gray-900 dark:text-dark-text-primary", children: t("mcp.title") })] }), expanded ? (_jsx(ChevronUp, { className: "w-5 h-5 text-gray-400 dark:text-dark-text-muted" })) : (_jsx(ChevronDown, { className: "w-5 h-5 text-gray-400 dark:text-dark-text-muted" }))] }), expanded && (_jsx("div", { className: "p-5 pt-0 space-y-4", children: _jsxs("div", { className: "space-y-2", children: [_jsxs("div", { className: "flex items-center justify-between mb-3", children: [_jsx("p", { className: "text-sm text-gray-600 dark:text-dark-text-secondary", children: t("mcp.description") }), _jsxs("button", { onClick: onAddServer, className: "flex items-center gap-2 px-3 py-1.5 bg-emerald-600 hover:bg-emerald-700 text-white rounded-lg transition-colors text-sm font-medium", children: [_jsx(Plus, { className: "w-4 h-4" }), t("mcp.addServer")] })] }), Object.keys(mcpServersConfig).length > 0 ? (_jsx("div", { className: "grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-3", children: Object.entries(mcpServersConfig).map(([serverId, server]) => {
                                const isHttpMode = !!server.url;
                                const isEnabled = !server.disabled;
                                return (_jsx("div", { className: `group rounded-lg border transition-all hover:shadow-md ${isEnabled
                                        ? "bg-emerald-50 dark:bg-emerald-900/20 border-emerald-200 dark:border-emerald-500/50"
                                        : "bg-gray-50 dark:bg-dark-bg-card border-gray-200 dark:border-dark-border-subtle"}`, children: _jsx("div", { className: "w-full p-4 text-left", children: _jsxs("div", { className: "flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2 flex-1 cursor-pointer", onClick: () => onEditServer({
                                                        isOpen: true,
                                                        serverId,
                                                        server,
                                                        mode: "edit",
                                                    }), children: [_jsx("div", { className: `p-2 rounded-lg ${isEnabled
                                                                ? "bg-emerald-100 dark:bg-emerald-900/30"
                                                                : "bg-gray-100 dark:bg-dark-bg-hover"}`, children: isHttpMode ? (_jsx(Globe, { className: `w-5 h-5 ${isEnabled
                                                                    ? "text-emerald-600 dark:text-emerald-400"
                                                                    : "text-gray-400 dark:text-dark-text-muted"}` })) : (_jsx(Terminal, { className: `w-5 h-5 ${isEnabled
                                                                    ? "text-emerald-600 dark:text-emerald-400"
                                                                    : "text-gray-400 dark:text-dark-text-muted"}` })) }), _jsxs("div", { className: "min-w-0 flex-1", children: [_jsx("h3", { className: "font-semibold text-gray-900 dark:text-dark-text-primary text-sm truncate", title: serverId, children: serverId }), _jsxs("div", { className: "flex items-center gap-2 mt-0.5", children: [_jsx("p", { className: "text-xs text-gray-500 dark:text-dark-text-muted", children: isHttpMode ? t("mcp.http") : t("mcp.stdio") }), isEnabled ? (_jsx("span", { className: "px-2 py-0.5 bg-emerald-100 dark:bg-emerald-900/30 text-emerald-700 dark:text-emerald-400 text-xs rounded-full whitespace-nowrap", children: t("config.enabled") })) : (_jsx("span", { className: "px-2 py-0.5 bg-gray-100 dark:bg-dark-bg-hover text-gray-600 dark:text-dark-text-muted text-xs rounded-full whitespace-nowrap", children: t("config.notEnabled") }))] })] })] }), _jsx("button", { onClick: (e) => {
                                                        e.stopPropagation();
                                                        onToggleServer(serverId);
                                                    }, className: `relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${isEnabled ? "bg-blue-600" : "bg-gray-300 dark:bg-dark-border-default"}`, title: isEnabled ? t("config.clickToDisable") : t("config.clickToEnable"), children: _jsx("span", { className: `inline-block h-5 w-5 transform rounded-full bg-white dark:bg-dark-text-primary transition-transform shadow ${isEnabled ? "translate-x-5" : "translate-x-0.5"}` }) })] }) }) }, serverId));
                            }) })) : (_jsx(EmptyState, { icon: Plug, title: t("mcp.noServers"), description: t("mcp.noServersDesc") }))] }) }))] }));
}
